version: "3.8"

services:
  api:
    container_name: air-quality-api
    build: .
    image: anesmadani/air-quality-api:latest
    restart: always
    environment:
      MODEL_FILE: /app/models/risk_model.pkl
      DATA_FILE: /app/data/aq_clean.parquet
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /root/air-quality-health/data:/app/data
      - /root/air-quality-health/models:/app/models
      - /root/air-quality-health/logs:/app/logs
      - aq-mlflow:/app/mlruns
    networks:
      airq_net:
        aliases:
          - air-quality-api

  mlflow-ui:
    container_name: mlflow-ui
    image: anesmadani/air-quality-api:latest
    restart: always
    depends_on:
      - api
    command: mlflow ui --backend-store-uri /app/mlruns --host 0.0.0.0 --port 5000
    environment:
      - MLFLOW_SERVER_ALLOWED_HOSTS=*
    ports:
      - "5000:5000"
    volumes:
      - aq-mlflow:/app/mlruns
    networks: [airq_net]

volumes:
  aq-mlflow:

networks:
  airq_net:
    external: true
