version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [airq_net]

  airflow-webserver:
    image: anesmadani/air-quality-airflow:latest
    restart: always
    command: webserver
    depends_on:
      - postgres
      - airflow-scheduler
    env_file:
      - /root/air-quality-health/airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__WEBSERVER__SECRET_KEY: "something_stupid_and_long"
      PYTHONPATH: /opt/airflow
      AIR_QUALITY_API_BASE_URL: http://api:8000
      MLFLOW_TRACKING_URI: "file:/app/mlruns"
    volumes:
      - /root/air-quality-health/airflow/dags:/opt/airflow/dags
      - /root/air-quality-health/airflow/logs:/opt/airflow/logs
      - /root/air-quality-health/airflow/plugins:/opt/airflow/plugins
      - /root/air-quality-health/airflow/src:/opt/airflow/src
      - /root/air-quality-health/data:/opt/airflow/data
      - /root/air-quality-health/models:/opt/airflow/models
      - aq-mlflow:/app/mlruns
    ports:
      - "8080:8080"
    networks: [airq_net]

  airflow-scheduler:
    image: anesmadani/air-quality-airflow:latest
    restart: always
    command: scheduler
    depends_on:
      - postgres
    env_file:
      - /root/air-quality-health/airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "something_stupid_and_long"
      PYTHONPATH: /opt/airflow
      AIR_QUALITY_API_BASE_URL: http://api:8000
      MLFLOW_TRACKING_URI: "file:/app/mlruns"
    volumes:
      - /root/air-quality-health/airflow/dags:/opt/airflow/dags
      - /root/air-quality-health/airflow/logs:/opt/airflow/logs
      - /root/air-quality-health/airflow/plugins:/opt/airflow/plugins
      - /root/air-quality-health/airflow/src:/opt/airflow/src
      - /root/air-quality-health/data:/opt/airflow/data
      - /root/air-quality-health/models:/opt/airflow/models
      - aq-mlflow:/app/mlruns
    networks: [airq_net]

volumes:
  postgres_data:
  aq-mlflow:

networks:
  airq_net:
    external: true