version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [airq_net]

  airflow-webserver:
    image: anesmadani/air-quality-airflow:latest
    restart: always
    command: ["airflow", "webserver"]
    depends_on: [postgres]
    env_file:
      - /root/air-quality-health/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__WEB_SERVER_HOST: "0.0.0.0"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"
      PYTHONPATH: /opt/airflow
    volumes:
      - /root/air-quality-health/airflow/dags:/opt/airflow/dags
      - /root/air-quality-health/airflow/logs:/opt/airflow/logs
      - /root/air-quality-health/airflow/plugins:/opt/airflow/plugins
      - /root/air-quality-health/src:/opt/airflow/src
    ports:
      - "8080:8080"
    networks: [airq_net]

  airflow-scheduler:
    image: anesmadani/air-quality-airflow:latest
    restart: always
    command: ["airflow", "scheduler"]
    depends_on: [postgres]
    env_file:
      - /root/air-quality-health/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow
    volumes:
      - /root/air-quality-health/airflow/dags:/opt/airflow/dags
      - /root/air-quality-health/airflow/logs:/opt/airflow/logs
      - /root/air-quality-health/airflow/plugins:/opt/airflow/plugins
      - /root/air-quality-health/src:/opt/airflow/src
    networks: [airq_net]

volumes:
  postgres_data:

networks:
  airq_net:
    external: true