name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build + Push images
        run: |
          docker build -t anesmadani/air-quality-api:${{ github.sha }} ./
          docker push anesmadani/air-quality-api:${{ github.sha }}
          docker build -t anesmadani/air-quality-airflow:${{ github.sha }} ./airflow
          docker push anesmadani/air-quality-airflow:${{ github.sha }}

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root/air-quality-health
            git fetch origin main
            git reset --hard origin/main
            docker-compose down
            docker system prune -af
            docker-compose pull
            docker network inspect airq_net >/dev/null 2>&1 || docker network create airq_net
            docker-compose up -d