name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build + Push images (sha + latest)
        run: |
          set -e
          docker build -t anesmadani/air-quality-api:${{ github.sha }} -t anesmadani/air-quality-api:latest ./
          docker push anesmadani/air-quality-api:${{ github.sha }}
          docker push anesmadani/air-quality-api:latest

          docker build -t anesmadani/air-quality-airflow:${{ github.sha }} -t anesmadani/air-quality-airflow:latest ./airflow
          docker push anesmadani/air-quality-airflow:${{ github.sha }}
          docker push anesmadani/air-quality-airflow:latest

      - name: SSH Deploy (API stack + Airflow stack)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e

            cd /root/air-quality-health
            git fetch origin main
            git reset --hard origin/main

            docker-compose down || true
            cd /root/air-quality-health/airflow && docker-compose down || true

            docker system prune -af

            docker network inspect airq_net >/dev/null 2>&1 || docker network create airq_net

            cd /root/air-quality-health
            docker-compose pull
            docker-compose up -d

            cd /root/air-quality-health/airflow
            docker-compose pull
            docker-compose up -d
